language: php

php:
  - 7.3
  - 7.4
  - nightly
  - hhvm

matrix:
  allow_failures:
    - php: hhvm
    - php: nightly
  include:
    - php: 7.3
      env:
        - COMPOSER_FLAGS="--prefer-lowest --prefer-stable"
        - COVERAGE=true
        - PHPUNIT_FLAGS="--coverage-clover=coverage.clover"

install:
  - travis_retry composer update ${COMPOSER_FLAGS} --prefer-source --no-interaction

script:
  - vendor/bin/phpspec run ${PHPSPEC_FLAGS}

after_script:
  - if [[ "$COVERAGE" = true ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ "$COVERAGE" = true ]]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
